package pedidos.com.pe.datos.entidades;
// Generated 16/04/2019 09:38:29 PM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Destinatario generated by hbm2java
 */
@Entity
@Table(name = "Destinatario", catalog = "pedido_db")
public class Destinatario implements java.io.Serializable {

	private Integer iddestinatario;
	private String nombres;
	private String apellidos;
	private String direccion;
	private Set<Pedido> pedidos = new HashSet<Pedido>(0);

	public Destinatario() {
	}

	public Destinatario(String apellidos) {
		this.apellidos = apellidos;
	}

	public Destinatario(String nombres, String apellidos, String direccion, Set<Pedido> pedidos) {
		this.nombres = nombres;
		this.apellidos = apellidos;
		this.direccion = direccion;
		this.pedidos = pedidos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "iddestinatario", unique = true, nullable = false)
	public Integer getIddestinatario() {
		return this.iddestinatario;
	}

	public void setIddestinatario(Integer iddestinatario) {
		this.iddestinatario = iddestinatario;
	}

	@Column(name = "nombres", length = 100)
	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	@Column(name = "apellidos", nullable = false, length = 100)
	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	@Column(name = "direccion", length = 100)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "destinatario")
	public Set<Pedido> getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set<Pedido> pedidos) {
		this.pedidos = pedidos;
	}

}
