package pedidos.com.pe.datos.entidades;
// Generated 16/04/2019 09:38:29 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pedido generated by hbm2java
 */
@Entity
@Table(name = "Pedido", catalog = "pedido_db")
public class Pedido implements java.io.Serializable {

	private Integer idpedido;
	private Cliente cliente;
	private Destinatario destinatario;
	private String nropedido;
	private Date fecha;
	private Double montopedido;
	private Set<DetallePedido> detallePedidos = new HashSet<DetallePedido>(0);

	public Pedido() {
	}

	public Pedido(Cliente cliente, Destinatario destinatario, String nropedido, Date fecha) {
		this.cliente = cliente;
		this.destinatario = destinatario;
		this.nropedido = nropedido;
		this.fecha = fecha;
	}

	public Pedido(Cliente cliente, Destinatario destinatario, String nropedido, Date fecha, Double montopedido,
			Set<DetallePedido> detallePedidos) {
		this.cliente = cliente;
		this.destinatario = destinatario;
		this.nropedido = nropedido;
		this.fecha = fecha;
		this.montopedido = montopedido;
		this.detallePedidos = detallePedidos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idpedido", unique = true, nullable = false)
	public Integer getIdpedido() {
		return this.idpedido;
	}

	public void setIdpedido(Integer idpedido) {
		this.idpedido = idpedido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcliente", nullable = false)
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iddestinatario", nullable = false)
	public Destinatario getDestinatario() {
		return this.destinatario;
	}

	public void setDestinatario(Destinatario destinatario) {
		this.destinatario = destinatario;
	}

	@Column(name = "nropedido", nullable = false, length = 10)
	public String getNropedido() {
		return this.nropedido;
	}

	public void setNropedido(String nropedido) {
		this.nropedido = nropedido;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 19)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "montopedido", precision = 22, scale = 0)
	public Double getMontopedido() {
		return this.montopedido;
	}

	public void setMontopedido(Double montopedido) {
		this.montopedido = montopedido;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pedido")
	public Set<DetallePedido> getDetallePedidos() {
		return this.detallePedidos;
	}

	public void setDetallePedidos(Set<DetallePedido> detallePedidos) {
		this.detallePedidos = detallePedidos;
	}

}
