package pedidos.com.pe.datos.entidades;
// Generated 16/04/2019 09:38:29 PM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name = "Producto", catalog = "pedido_db")
public class Producto implements java.io.Serializable {

	private Integer idproducto;
	private String nombre;
	private Integer cantidad;
	private Double precio;
	private Set<DetallePedido> detallePedidos = new HashSet<DetallePedido>(0);

	public Producto() {
	}

	public Producto(String nombre, Integer cantidad, Double precio, Set<DetallePedido> detallePedidos) {
		this.nombre = nombre;
		this.cantidad = cantidad;
		this.precio = precio;
		this.detallePedidos = detallePedidos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idproducto", unique = true, nullable = false)
	public Integer getIdproducto() {
		return this.idproducto;
	}

	public void setIdproducto(Integer idproducto) {
		this.idproducto = idproducto;
	}

	@Column(name = "nombre", length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "cantidad")
	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "precio", precision = 22, scale = 0)
	public Double getPrecio() {
		return this.precio;
	}

	public void setPrecio(Double precio) {
		this.precio = precio;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "producto")
	public Set<DetallePedido> getDetallePedidos() {
		return this.detallePedidos;
	}

	public void setDetallePedidos(Set<DetallePedido> detallePedidos) {
		this.detallePedidos = detallePedidos;
	}

}
